name: release-binaries
on:
  release:
    types: [published]

jobs:
  linux-x86_64-musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/x86_64-unknown-linux-musl/release
          strip rsgrad
          chmod +x rsgrad
          tar -c rsgrad | gzip > rsgrad.tar.gz
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rsgrad-${{ github.event.release.tag_name }}-linux-x86_64-musl.tar.gz
          asset_path: target/x86_64-unknown-linux-musl/release/rsgrad.tar.gz
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/zip

  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/release
          strip rsgrad
          chmod +x rsgrad
          tar -c rsgrad | gzip > rsgrad.tar.gz
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rsgrad-${{ github.event.release.tag_name }}-linux-x86_64.tar.gz
          asset_path: target/release/rsgrad.tar.gz
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/zip

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true
          
      - name: Optimize and package binary
        run: |
          cd target/release
          strip rsgrad
          chmod +x rsgrad
          tar -c rsgrad | gzip > rsgrad.tar.gz

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rsgrad-${{ github.event.release.tag_name }}-macos-x86_64.tar.gz
          asset_path: target/release/rsgrad.tar.gz
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/zip

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/release
          7z a rsgrad.zip rsgrad.exe

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: rsgrad-${{ github.event.release.tag_name }}-windows-x86_64.zip
          asset_path: target/release/rsgrad.zip
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/zip
