#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from kpoints import *
import os
import sys
file_in  = 'POSCAR'
file_out = 'KPOINTS'

if len(sys.argv[:]) == 1: 
    '''Only the comamnd kp.py are input by user '''
    if os.path.isfile(file_in):
        if not os.path.isfile(file_out):
            print('\nQ-robot did not find the KPOINTS file. \n\n Now I am going to generate a new one!\n \n')
            generate_kpoints(file_out)
        else:  
            print('\n%s has already exist\n' %(file_out))
            print('\nOnly print the %s information\n' %(file_out))

            read_kpoints()
    else:
        print('\nQ-robot did not find the POSCAR file.')
        if not os.path.isfile(file_out):
            print('\n Q-robot did not find the KPOINTS file.')
            print('\nA 3 3 1 KPOINTS will be generated by default!\n')
            generate_kpoints_by_hands(3, 3, 1)
        else:  
            print('\n%s has already exist:' %(file_out))
            print('\nOnly print the %s information\n' %(file_out))
            read_kpoints()
                
elif len(sys.argv[:]) == 4: 
    try: 
        k_a, k_b, k_c = [int(i) for i in sys.argv[1:]]
        generate_kpoints_by_hands(k_a, k_b, k_c)
#        read_kpoints('KPOINTS')
    except ValueError: 
        print('Please input the numbers for KPOINS')
        exit()
else:
    print('\n \n Command usages: \n\n 1) To generate KPOINTS by using Q-robot:\t kp.py \n\n 2) To generate specified KPOINTS of 3 3 1:\t kp.py 3 3 1 \n\n ' )
        
        
         
                                                       
