#!/usr/bin/env python3
'''Generate POTCAR files '''
import sys, os
from potcar import *

#Check if POSCAR in the folder
is_poscar_here = False
if os.path.isfile('POSCAR'):
    is_poscar_here = True

if len(sys.argv[:]) == 1: 
    '''Auto mode by reading the POSCAR'''
    if is_poscar_here:
        print('POTCAR is Generated by reading POSCAR!')
        poscar =  open('POSCAR', 'r')
        lines = poscar.readlines()
        poscar.close()
        ele_list =  lines[5].rstrip().split()  ## Read the element line
        if ele_list[0].isdigit():  
            '''For VASP4 and ASE type POSCAR without elements in line 6'''
            print('\nPOSCAR Format: VASP4\n')
            ele_list = lines[0].rstrip().split()    
        concatenate(ele_list)
        read_potcar('POTCAR')
    else: 
        print('%s' %('%' * 40))
        print('\nWARNING!!!'*3 )# * 2 )
        print('''\nPOTCAR CANNOT be automatically generated due to the missing POSCAR!!!\n
But you can make it by using command below:\n
pp.py element1 element2 ....\n''')
        print('%s' %('%' * 40))  

if len(sys.argv)  > 1 :
    '''Make POTCAR manually.'''
    ele_list = sys.argv[1:] 
    concatenate(ele_list)
    read_potcar('POTCAR')